/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import static clases.conectar.con;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author artea
 */
public class Actividades_recientes extends javax.swing.JPanel {
ArrayList<JLabel> botones;
//Font f = new Font("Tahoma",1,18);
Font f = new Font("Segoe UI Semibold",1,24);
//Segoe UI Semibold
//font	Segoe UI Semibold 20 Negrita

    /**
     * Creates new form Actividades_recientes
     */
    public Actividades_recientes() {
        initComponents();
        jPanel1.setPreferredSize(new Dimension(800, 1100));
        botones = new ArrayList<>();
    try {
        mo();
    } catch (SQLException ex) {
        Logger.getLogger(Actividades_recientes.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        mostrar();
    } catch (SQLException ex) {
        Logger.getLogger(Actividades_recientes.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    public void mostrar() throws SQLException{
        ResultSet rs = null;
        Statement st = con.createStatement();
        rs = st.executeQuery("select * from registro");
        while(rs.next()){
            JLabel label = new JLabel(rs.getString("ID")+" - "+rs.getString("evento"));
            label.setFont(f);
            label.setForeground(Color.BLACK);
            jPanel1.add(label);
            botones.add(label);
            jPanel1.updateUI();
        }
    }
    public void mo() throws SQLException{
        ResultSet rs = null;
        Statement st = con.createStatement();
        rs = st.executeQuery("select * from registro");
        while(rs.next()){
            txtactividades.append(rs.getString("ID")+" - "+rs.getString("evento") +"\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtactividades = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtactividades.setEditable(false);
        txtactividades.setColumns(20);
        txtactividades.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        txtactividades.setRows(5);
        txtactividades.setBorder(null);
        jScrollPane1.setViewportView(txtactividades);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 670));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(25, 0));
        jScrollPane2.setViewportView(jPanel1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, 10, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtactividades;
    // End of variables declaration//GEN-END:variables
}
