/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import static clases.conectar.con;
import static clases.menu.panelprincipal;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author artea
 */
public class agregarbuses extends javax.swing.JPanel {
conectar cc = new conectar();
DefaultTableModel modelo1;
String inicio, fin;
String tipo;
    /**
     * Creates new form agregarbuses
     */
    public agregarbuses() {
        initComponents();
        jButton1.hide();
    try {
        aggParadas();
    } catch (SQLException ex) {
        Logger.getLogger(agregarbuses.class.getName()).log(Level.SEVERE, null, ex);
    }
    t_datos.setRowHeight(30);
    }
        public void cargar_color(){
        if("".equals(txtcolor.getText())){
            txtcolor.setText("#FFFFFF");
        }
        else{
            Color c = Color.decode(txtcolor.getText());
            txtcolor.setBackground(c);
        }
    }
        public  void agg_bus() throws SQLException{
        String [] titulos={"N°","PARADAS"};
        String [] w = new String[8];
         modelo1 = (DefaultTableModel) t_datos.getModel();
                  w[0]=txtruta.getText();
                  w[1]=txttiempo.getText();
                  w[2]=txtprecio.getText();
                  w[3]=(String)cbxtipo.getSelectedItem();
                  w[4]=txtviajes.getText();
                  w[5]=inicio;
                  w[6]=fin;
                  w[7]=txtcolor.getText();
                  modelo1.addRow(w);
                  t_datos.setModel(modelo1);
    }
        public void aggParadas() throws SQLException{
            ResultSet rs = null;
            PreparedStatement st = con.prepareStatement("select * from paradas");
            rs = st.executeQuery();
            while(rs.next()){
                cbxparadas.addItem(rs.getString(1));
            }
        }
        public void inicio(){
            panelprincipal.setVisible(true);
        inicio v = new inicio();
        v.setSize(1100, 900);
        v.setLocation(5, 5);
        panelprincipal.setVisible(true);
        panelprincipal.removeAll();
        panelprincipal.add(v, BorderLayout.CENTER);
        panelprincipal.revalidate();
        panelprincipal.repaint();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtruta = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txttiempo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtviajes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtinicio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtcolor = new javax.swing.JTextField();
        bntguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        cbxampm = new javax.swing.JComboBox<>();
        cbxampm1 = new javax.swing.JComboBox<>();
        cbxtipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_datos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cbxparadas = new javax.swing.JComboBox<>();
        txtcodigo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtempresario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("CODIGO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        txtruta.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        add(txtruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 211, -1));

        txtprecio.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 70, -1));

        txttiempo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        add(txttiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 211, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("TIPO");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        txtviajes.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        add(txtviajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("N° VIAJES");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("PRECIO");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("TIEMPO");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 70, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("INICIO");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        txtinicio.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        add(txtinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 130, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("FINAL");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        txtfin.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        add(txtfin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 130, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("PARADA");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        txtcolor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtcolor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcolorMouseClicked(evt);
            }
        });
        txtcolor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcolorKeyTyped(evt);
            }
        });
        add(txtcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 130, -1));

        bntguardar.setBackground(new java.awt.Color(0, 0, 0));
        bntguardar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bntguardar.setForeground(new java.awt.Color(255, 255, 255));
        bntguardar.setText("GUARDAR");
        bntguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntguardarActionPerformed(evt);
            }
        });
        add(bntguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 160, 50));

        btncancelar.setBackground(new java.awt.Color(0, 0, 0));
        btncancelar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("CANCELAR");
        add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 160, 50));

        cbxampm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cbxampm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "am", "pm" }));
        add(cbxampm, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));

        cbxampm1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cbxampm1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "am", "pm" }));
        add(cbxampm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        cbxtipo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        cbxtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bus", "Microbús" }));
        add(cbxtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel3.setText("$");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        t_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUTA", "TIEMPO", "PRECIO $", "TIPO", "VIAJES", "INICIO", "FINAL", "COLOR"
            }
        ));
        jScrollPane1.setViewportView(t_datos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 740, 220));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("COLOR");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        cbxparadas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(cbxparadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 140, -1));

        txtcodigo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 211, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("RUTA");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        txtempresario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtempresario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtempresarioMouseClicked(evt);
            }
        });
        txtempresario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtempresarioKeyTyped(evt);
            }
        });
        add(txtempresario, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 130, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("EMPRESARIO");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bntguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntguardarActionPerformed
    inicio = txtinicio.getText() +" "+(String) cbxampm.getSelectedItem();
    fin = txtfin.getText() +" "+ (String)cbxampm1.getSelectedItem();
    tipo = (String) cbxtipo.getSelectedItem();
    try {
        cc.insertBusParada((String) cbxparadas.getSelectedItem(), txtcodigo.getText(), txtruta.getText(), txttiempo.getText(), txtprecio.getText(), tipo, txtviajes.getText(), inicio, fin, txtcolor.getText(), txtempresario.getText());
        //cc.insertBusParada((String) cbxparadas.getSelectedItem(),txtruta.getText(),txttiempo.getText() ,txtprecio.getText() ,tipo ,txtviajes.getText() ,inicio ,fin,txtcolor.getText());
        agg_bus();
        JOptionPane.showMessageDialog(null, "Bus agregado con éxito");
        inicio();
    } catch (SQLException ex) {
        Logger.getLogger(agregarbuses.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_bntguardarActionPerformed

    private void txtcolorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcolorMouseClicked
        Color c = JColorChooser.showDialog(null, "Elije un color",this.getBackground());
        txtcolor.setText("#"+Integer.toHexString(c.getRGB() & 0x00ffffff));
        txtcolor.setBackground(c);
    }//GEN-LAST:event_txtcolorMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cargar_color();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcolorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcolorKeyTyped
        char tecla  = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ENTER) {
              jButton1.doClick();
          }
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_txtcolorKeyTyped

    private void txtempresarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtempresarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempresarioMouseClicked

    private void txtempresarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtempresarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempresarioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntguardar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JComboBox<String> cbxampm;
    private javax.swing.JComboBox<String> cbxampm1;
    private javax.swing.JComboBox<String> cbxparadas;
    private javax.swing.JComboBox<String> cbxtipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_datos;
    public static javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtempresario;
    private javax.swing.JTextField txtfin;
    private javax.swing.JTextField txtinicio;
    private javax.swing.JTextField txtprecio;
    public static javax.swing.JTextField txtruta;
    private javax.swing.JTextField txttiempo;
    private javax.swing.JTextField txtviajes;
    // End of variables declaration//GEN-END:variables
}
