/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

/**
 *
 * @author Isaac
 */
public class AgregarCal extends javax.swing.JPanel {

    /**
     * Creates new form AgregarCal
     */
    public AgregarCal() {
        
        initComponents();
        Transparencia();
    }

    
    
    
    public void Transparencia(){
        gua.setOpaque(false);
        gua.setContentAreaFilled(false);
        gua.setBorderPainted(false);


        canc.setOpaque(false);
        canc.setContentAreaFilled(false);
        canc.setBorderPainted(false);

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gua = new javax.swing.JButton();
        canc = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        jLabel1.setText("DESCRIPCION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        jLabel2.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        jLabel2.setText("INICIO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        jLabel3.setText("FIN");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        gua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buses/button(25).png"))); // NOI18N
        gua.setBorder(null);
        gua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gua.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buses/button(29).png"))); // NOI18N
        add(gua, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        canc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buses/button(26).png"))); // NOI18N
        canc.setBorder(null);
        canc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        canc.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/buses/button(27).png"))); // NOI18N
        canc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancActionPerformed(evt);
            }
        });
        add(canc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 300, 60));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 300, 30));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 310, 30));

        jCheckBox1.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        jCheckBox1.setText("DOMINGO");
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        jCheckBox2.setText("LUNES");
        add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        jCheckBox3.setText("MARTES");
        add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jCheckBox4.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        jCheckBox4.setText("JUEVES");
        add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jCheckBox5.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        jCheckBox5.setText("VIERNES");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        jCheckBox6.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        jCheckBox6.setText("SABADO");
        add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        jCheckBox7.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        jCheckBox7.setText("MIERCOLES");
        add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 50, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void cancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canc;
    private javax.swing.JButton gua;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
