/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import static clases.conectar.con;
import static clases.menu.jLabel5;
import static clases.menu.panelprincipal;
import java.awt.BorderLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author artea
 */
public class bus extends javax.swing.JPanel {
conectar cc = new conectar();
DefaultTableModel modelo1;
tablabuses tt = new tablabuses();
    /**
     * Creates new form bus
     */
    public bus() {
        initComponents();
        Transparencia();
        t_buses.setRowHeight(30);
        //tt.mostrar_t(t_buses);
    try {
        mostrarbuses(txtbuscar.getText());
    } catch (SQLException ex) {
        Logger.getLogger(bus.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    public  void mostrarbuses(String buscar) throws SQLException{
        String [] titulos={"TIPO","BUS","VIAJES","ACTUALIZACION", "ACCIONES"};
        String [] w = new String[5];
        String sql = "SELECT * FROM buses WHERE LOWER(nombre) LIKE LOWER('%"+buscar+"%') AND TIPO IS NOT NULL";
         modelo1 = new DefaultTableModel(null,titulos);
        
         try {
              Statement st = con.createStatement();
              ResultSet rs = st.executeQuery(sql);
              while (rs.next()){
                  w[0]=rs.getString("tipo");
                  w[1]=rs.getString("nombre");
                  w[2]=rs.getString("viajes");
                  w[3]=rs.getString("parada");
//                  w[4]=rs.getString("precio");
                  modelo1.addRow(w);
              }
              t_buses.setModel(modelo1);
              
         } catch (SQLException e) {
             JOptionPane.showMessageDialog(null, e);
         } 
    }
    public void Transparencia(){
        btnaggb.setOpaque(false);
        btnaggb.setContentAreaFilled(false);
        btnaggb.setBorderPainted(false);
        
        btneditar.setOpaque(false);
        btneditar.setContentAreaFilled(false);
        btneditar.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnaggb = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_buses = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        cbxdias = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxregistros = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btneditar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(685, 443));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnaggb.setBackground(new java.awt.Color(0, 0, 102));
        btnaggb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnaggb.setForeground(new java.awt.Color(255, 255, 255));
        btnaggb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buses/button(18).png"))); // NOI18N
        btnaggb.setBorder(null);
        btnaggb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaggb.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buses/button(19).png"))); // NOI18N
        btnaggb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaggbActionPerformed(evt);
            }
        });
        jPanel1.add(btnaggb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 200, 50));

        t_buses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_buses.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        t_buses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TIPO", "BUS", "VIAJES", "ACTUALIZACIÓN", "ACCIONES"
            }
        ));
        t_buses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_busesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_buses);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 910, 340));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("REGISTROS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, -1, -1));

        txtbuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 300, -1));

        cbxdias.setBackground(new java.awt.Color(153, 153, 153));
        cbxdias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxdias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos los dias", "Dias Laborales", "Festivos" }));
        jPanel1.add(cbxdias, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 130, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("BUSCAR:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        cbxregistros.setBackground(new java.awt.Color(153, 153, 153));
        cbxregistros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxregistros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "25", "50", "100" }));
        jPanel1.add(cbxregistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("MOSTRAR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        btneditar.setBackground(new java.awt.Color(0, 0, 102));
        btneditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btneditar.setForeground(new java.awt.Color(255, 255, 255));
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buses/button(20).png"))); // NOI18N
        btneditar.setBorder(null);
        btneditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneditar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buses/button(21).png"))); // NOI18N
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        jPanel1.add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 200, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void t_busesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_busesMouseClicked
        int column = t_buses.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/t_buses.getRowHeight();
        if(row < t_buses.getRowCount() && row >= 0 && column < t_buses.getColumnCount() && column >= 0){
            Object value = t_buses.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value; 
                if(boton.getName().equals("h")){
                    JOptionPane.showMessageDialog(null, "Viendo Horarios");
                }
                if(boton.getName().equals("ed")){
                    JOptionPane.showMessageDialog(null, "Editando");
                } 
            }
        }
    }//GEN-LAST:event_t_busesMouseClicked

    private void btnaggbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaggbActionPerformed
        panelprincipal.setVisible(true);
        agregarbuses aa = new agregarbuses();
        aa.setSize(1100, 900);
        aa.setLocation(5, 5);
        panelprincipal.setVisible(true);
        panelprincipal.removeAll();
        panelprincipal.add(aa, BorderLayout.CENTER);
        panelprincipal.revalidate();
        panelprincipal.repaint();
        agregarbuses.txtruta.requestFocus();
        jLabel5.setText(btnaggb.getText());
    }//GEN-LAST:event_btnaggbActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
    try {
        mostrarbuses(txtbuscar.getText());
    } catch (SQLException ex) {
        Logger.getLogger(bus.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        panelprincipal.setVisible(true);
        Editar_bus aa = new Editar_bus();
        aa.setSize(1100, 900);
        aa.setLocation(5, 5);
        panelprincipal.setVisible(true);
        panelprincipal.removeAll();
        panelprincipal.add(aa, BorderLayout.CENTER);
        panelprincipal.revalidate();
        panelprincipal.repaint();
        jLabel5.setText(btneditar.getText());
    }//GEN-LAST:event_btneditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaggb;
    private javax.swing.JButton btneditar;
    private javax.swing.JComboBox<String> cbxdias;
    private javax.swing.JComboBox<String> cbxregistros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_buses;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
