/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

/**
 *
 * @author Isaac
 */
public class Calendario extends javax.swing.JPanel {

    /**
     * Creates new form Calendario
     */
    public Calendario() {
        initComponents();
        
        Transparencia();
    }

    public void Transparencia(){
        agre.setOpaque(false);
        agre.setContentAreaFilled(false);
        agre.setBorderPainted(false);
        }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1050, 740));
        setPreferredSize(new java.awt.Dimension(1050, 740));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buses/button(22).png"))); // NOI18N
        agre.setBorder(null);
        agre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agre.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buses/button(23).png"))); // NOI18N
        add(agre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 270, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Buscar");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 70, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 330, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Mostrar");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 690, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
