/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import static clases.conectar.con;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author artea
 */
public class Editar_bus extends javax.swing.JPanel {
conectar cc = new conectar();
DefaultTableModel modelo1;
    /**
     * Creates new form Editar_bus
     */
    public Editar_bus() {
        initComponents();
        t_buses.setRowHeight(30);
    try {
        mostrarbuses(txtbuscar.getText());
    } catch (SQLException ex) {
        Logger.getLogger(Editar_bus.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }
    public  void mostrarbuses(String buscar) throws SQLException{
        String [] titulos={"CODIGO","BUS","VIAJES","PARADA", "ACCIONES"};
        String [] w = new String[5];
        String sql = "SELECT * FROM buses WHERE LOWER(nombre) LIKE LOWER('%"+buscar+"%') AND TIPO IS NOT NULL";
         modelo1 = new DefaultTableModel(null,titulos);
        
         try {
              Statement st = con.createStatement();
              ResultSet rs = st.executeQuery(sql);
              while (rs.next()){
                  w[0]=rs.getString("codigo");
                  w[1]=rs.getString("nombre");
                  w[2]=rs.getString("viajes");
                  w[3]=rs.getString("parada");
                  modelo1.addRow(w);
              }
              t_buses.setModel(modelo1);
              modelo1.addTableModelListener(new TableModelListener() {
                  @Override
                  public void tableChanged(TableModelEvent e) {
                      if(e.getType() == TableModelEvent.UPDATE){
                          int columna = e.getColumn();
                          int fila = e.getFirstRow();
                          if(columna == 1){
                              try {
                                  //JOptionPane.showMessageDialog(null, t_buses.getValueAt(fila, 1).toString());
                                  cc.updateBus2(t_buses.getValueAt(fila, 0).toString(), t_buses.getValueAt(fila, columna).toString());
//                                  String sql="update buses set nombre = '" + t_buses.getValueAt(fila, columna).toString() + "' where nombre = '" + t_buses.getValueAt(fila, 1).toString()+"'";
//                                  con.createStatement().executeUpdate(sql);
                                  mostrarbuses(txtbuscar.getText());
                                  //JOptionPane.showMessageDialog(null, "Bus " + t_buses.getValueAt(fila, 1).toString() +" Modificado a: " + t_buses.getValueAt(fila, columna).toString());
                              } catch (Exception ex) {
                                  Logger.getLogger(Editar_bus.class.getName()).log(Level.SEVERE, null, ex);
                              }
                          }
                      }
                      //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                  }
              });
         } catch (SQLException e) {
             JOptionPane.showMessageDialog(null, e);
         } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_buses = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_buses.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        t_buses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        t_buses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_busesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_buses);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 820, 350));

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 120, 50));

        txtbuscar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 240, 30));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 160, -1));

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        int fila = t_buses.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(null, "Seleccione un bus para eliminarlo");
        }
        else{
            cc.eliminarBus(modelo1.getValueAt(fila, 1).toString());
            JOptionPane.showMessageDialog(null, modelo1.getValueAt(fila, 1).toString()+" Eliminado Correctamente");
            mostrarbuses(txtbuscar.getText());
        }
    } catch (SQLException ex) {
        Logger.getLogger(Editar_bus.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
    try {
        mostrarbuses(txtbuscar.getText());
    } catch (SQLException ex) {
        Logger.getLogger(Editar_bus.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int filaSe = t_buses.getSelectedRow();
        int col = t_buses.getSelectedColumn();
        if(!(filaSe == -1)){
            try {
                cc.updateBus2(t_buses.getValueAt(filaSe, 0).toString(),jTextField1.getText());
                mostrarbuses(txtbuscar.getText());
                JOptionPane.showMessageDialog(null, "Bus Modificado");
            } catch (SQLException ex) {
                Logger.getLogger(Editar_bus.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione un Bus para modificarlo");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void t_busesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_busesMouseClicked
        int filaSe = t_buses.getSelectedRow();
        int col = t_buses.getSelectedColumn();
        if(!(filaSe == -1)){
            jTextField1.setText(t_buses.getValueAt(filaSe, 1).toString());
//            try {
//                cc.updateBus2(t_buses.getValueAt(filaSe, 0).toString(), t_buses.getValueAt(filaSe, col).toString());
//                JOptionPane.showMessageDialog(null, "Bus Modificado");
//            } catch (SQLException ex) {
//                Logger.getLogger(Editar_bus.class.getName()).log(Level.SEVERE, null, ex);
//            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione un Bus para modificarlo");
        }
    }//GEN-LAST:event_t_busesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable t_buses;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
