package clases;

import static clases.conectar.con;
import static clases.menu.jLabel5;
import static clases.menu.panelprincipal;
import static clases.paradas.txtparada;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author artea
 */
public class inicio extends javax.swing.JPanel {
ArrayList<JPanel> paneles;
ArrayList<JButton> botones;
conectar cc = new conectar();
Font f = new Font("Tahoma",1,18);
    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        
        jButton1.hide();
        cargar_color();
        paneles = new ArrayList<>();
        botones = new ArrayList<>();
//        jButton3.setMinimumSize(new Dimension(20,20));
//        jButton3.setMaximumSize(new Dimension(150,60));
//        jButton3.setPreferredSize(new Dimension(120,30));
        jPanel2.setPreferredSize(new Dimension(800, 800));
    try {
        mostrar();
    } catch (SQLException ex) {
        Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    public void cargar_color(){
        if("".equals(txtcolor.getText())){
            txtcolor.setText("#FFFFFF");
        }
        else{
            Color c = Color.decode(txtcolor.getText());
            txtcolor.setBackground(c);
            jLabel2.setForeground(c);
        }
        
    }
    public void agregar(){
        
        
    }
    public void crear(){
        //        JPanel panel = new JPanel();
//        jPanel2.add(panel);
//        paneles.add(panel);
//        jPanel2.updateUI();
    try {
        JButton boton = new JButton(txtparada.getText());
        cc.insertParada(txtparada.getText());
        txtparada.setText("");
        txtparada.requestFocus();
        jPanel2.add(boton);
        botones.add(boton);
        jPanel2.updateUI();
    } catch (SQLException ex) {
        Logger.getLogger(paradas.class.getName()).log(Level.SEVERE, null, ex);
    } 
    }
    public void mostrar() throws SQLException{
        
        ResultSet rs = null;
        Statement st = con.createStatement();
        rs = st.executeQuery("select * from paradas");
        while(rs.next()){
            JButton boton = new JButton(rs.getString("nombre"));
            boton.setFont(f);
            boton.setForeground(Color.WHITE);
            boton.setBackground(new Color(0, 0, 0));
            jPanel2.add(boton);
            botones.add(boton);
            jPanel2.updateUI();
            boton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    jLabel1.setText(boton.getText());
                    panelprincipal.setVisible(true);
        relacion aa = new relacion();
        aa.setSize(1100, 900);
        aa.setLocation(5, 5);
        panelprincipal.setVisible(true);
        panelprincipal.removeAll();
        panelprincipal.add(aa, BorderLayout.CENTER);
        panelprincipal.revalidate();
        panelprincipal.repaint();
        jLabel5.setText("Relacion Buses a Parada: " + boton.getText());
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcolor = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        txtparada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("BUS SIMULATOR xdxd");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buses/appbar.arrow.down.png"))); // NOI18N
        jLabel3.setText("Click Aqui xdxd");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, 45));

        txtcolor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtcolor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcolorMouseClicked(evt);
            }
        });
        txtcolor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcolorKeyTyped(evt);
            }
        });
        jPanel1.add(txtcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 141, -1));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(9, 2, 3, 3));
        jScrollPane1.setViewportView(jPanel2);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 1010, 530));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jPanel4.add(txtparada);

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 30, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 330, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtcolorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcolorMouseClicked
        Color c = JColorChooser.showDialog(null, "Elije un color",this.getBackground());
        txtcolor.setText("#"+Integer.toHexString(c.getRGB() & 0x00ffffff));
        txtcolor.setBackground(c);
        jLabel2.setForeground(c);
    }//GEN-LAST:event_txtcolorMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cargar_color();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcolorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcolorKeyTyped
        char tecla  = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ENTER) {
              jButton1.doClick();
          }
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c)){
            String cad = (""+c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_txtcolorKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //crear();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtcolor;
    private javax.swing.JTextField txtparada;
    // End of variables declaration//GEN-END:variables
}
